# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/clinica
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Config (Clave secreta para firmar tokens - cambiar en produccion)
clinica.app.jwtSecret=SecretKeySuperSeguraParaLaClinicaBackendConSpringSecurity2024
clinica.app.jwtExpirationMs=86400000

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
