server.port=29697

spring.datasource.url=postgresql://postgres:JmphnLclKiylNrOWLgEQJwmwAIOkKFwV@interchange.proxy.rlwy.net:29697/railway
spring.datasource.username=postgres
spring.datasource.password=JmphnLclKiylNrOWLgEQJwmwAIOkKFwV

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

clinica.app.jwtSecret=U2VjcmV0S2V5U3VwZXJTZWd1cmFQYXJhTGEyMDI0Q2xpbmljYUJhc2U=
clinica.app.jwtExpirationMs=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
